### ISSUE TITLE
Index Error when packaging Mu on Windows

### ISSUE THREAD

**Issue by ntoll** [mu-editor/pup#137] opened 2021-01-28 08:50 UTC
I started from a fresh up-to-date Windows 10. I'm using Python 3.9.1. I created a virtualenv, pip installed Mu's requirements.txt and then `pip install pup`, then `pup package mu-editor`. I get the following output:

```

(mu) C:\Users\ntoll\Documents\GitHub\mu>pup package mu-editor
I pup 1.0.0a8 - starting with PID=9656
I Package 'mu-editor': starting.
I Collecting metadata for 'mu-editor'.
I About to run 'c:\\users\\ntoll\\documents\\mu\\scripts\\python.exe -m pip wheel --no-deps C:\\Users\\ntoll\\Documents\\GitHub\\mu\\mu-editor'.
I pip err: ERROR: Invalid requirement: 'C:\\Users\\ntoll\\Documents\\GitHub\\mu\\mu-editor'
I pip err: Hint: It looks like a path. File 'C:\Users\ntoll\Documents\GitHub\mu\mu-editor' does not exist.
I pip err: WARNING: You are using pip version 20.2.3; however, version 21.0 is available.
I pip err: You should consider upgrading via the 'c:\users\ntoll\documents\mu\scripts\python.exe -m pip install --upgrade pip' command.
C Execution failure: list index out of range
C Traceback below:
Traceback (most recent call last):
  File "c:\users\ntoll\documents\mu\lib\site-packages\pup\__main__.py", line 31, in wrapper
    exit_code = command_function(*args, **kw)
  File "c:\users\ntoll\documents\mu\lib\site-packages\pup\__main__.py", line 80, in package
    return api.package(
  File "c:\users\ntoll\documents\mu\lib\site-packages\pup\api.py", line 55, in package
    dsp.collect_src_metadata()
  File "c:\users\ntoll\documents\mu\lib\site-packages\pup\dispatcher.py", line 94, in collect_src_metadata
    return self._invoke_plugin('pup.metadata')
  File "c:\users\ntoll\documents\mu\lib\site-packages\pup\dispatcher.py", line 68, in _invoke_plugin
    return plugin(self._ctx, self, **kwargs)
  File "c:\users\ntoll\documents\mu\lib\site-packages\pup\plugins\metadata.py", line 73, in __call__
    wheel_file = self._create_wheel(ctx.src, temp_dir, dsp)
  File "c:\users\ntoll\documents\mu\lib\site-packages\pup\plugins\metadata.py", line 95, in _create_wheel
    wheel_file = os.listdir()[0]
IndexError: list index out of range
I pup 1.0.0a8 - done

```

**Comment by tmontes** [comment] 2021-01-28 12:58
Thanks @ntoll for the report.

Preliminary notes:

* Usage is not as intended:
  * `pup` does not currently support Python 3.9.
  * To package Mu Editor from the root of the source repo the command would be `pup package .` (actually it needs the `--launch-module=mu` because it does not match the distribution name, which is `mu-editor`).

However, I'd expect such a command -- `pup package mu-editor` to work, much like `pip install mu-editor` should work... (then again, not sure, given that within the currently active venv `mu-editor` is already installed) -- Doing that should grab `mu-editor` from PyPI and package it. Certainly not what you intended.

Will investigate later but, at least for now, tagging as a doc bug. :-)

**Comment by tmontes** [comment] 2021-11-01 23:05
Actually, your usage should have worked -- not doing what you expected, but packaging `mu-editor` grabbed from PyPI instead.

PR #187, just merged, fixes the behaviour -- `pup` can now package directly from PyPI (whether that's valuable/interesting or not is a different matter!).

**Closed** 2021-11-01 23:06 UTC
Labels: bug, @ docs
