### ISSUE TITLE
Win MSI | Start menu shortcut without a folder?

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/pup#164] opened 2021-08-23 17:21 UTC
Just a small suggestion, very open to discussion or to be discarded.

I've noticed these days most of things (not all) I install on Windows end up with a single shortcut at the root of the start menu to open the programme.

Currently Mu ends up in a folder in the start menu, with a single item, which is the shortcut to open it.
Because the Mu icon is not used on the folder (it uses a normal folder icon), it makes it less obvious. It certainly takes me a bit more effort to find Mu. It's just a small observation, but taking in consideration I've had several reports about difficulties finding the way to launch Mu, every little helps.

<img width="49%" alt="image" src="https://user-images.githubusercontent.com/4189262/131106349-23c96069-8601-423e-bc94-54d23f385ec1.png"> <img width="49%" alt="image" src="https://user-images.githubusercontent.com/4189262/131106381-b7a11bc6-9fa0-4cee-b4c4-7307a238222d.png">

**Comment by tmontes** [comment] 2021-08-28 23:23
CLOSING as a duplicate of #147 -- being addressed as these words are written! :)

**Closed by tmontes** 2021-08-28 23:23 UTC

**Comment by tmontes** [comment] 2021-08-28 23:42
FYI, just merged PR #170 addressing this. :)
