### ISSUE TITLE
Win MSI | Uninstalling leaves some files behind

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/pup#162] opened 2021-08-13 09:58 UTC
After uninstalling Mu (from my experience in https://github.com/mu-editor/pup/issues/161) these files are left behind:

```
C:\Users\IEUser\AppData\Local\Programs\Mu Editor>tree /F
Folder PATH listing for volume Windows 10
Volume serial number is F00E-4EED
C:.
└───Python
    └───Lib
        └───site-packages
            ├───ipykernel-6.0.1.dist-info
            │       COPYING.md
            │       INSTALLER
            │       METADATA
            │       RECORD
            │       top_level.txt
            │       WHEEL
            │
            ├───mu
            │   └───wheels
            │           1.1.0.beta.5.zip
            │
            ├───mu_editor-1.1.0b5-py3.8.egg-info
            │       dependency_links.txt
            │       entry_points.txt
            │       installed-files.txt
            │       not-zip-safe
            │       PKG-INFO
            │       requires.txt
            │       SOURCES.txt
            │       top_level.txt
            │
            └───regex-2021.7.1.dist-info
                    INSTALLER
                    LICENSE.txt
                    METADATA
                    RECORD
                    top_level.txt
                    WHEEL
```

When the user uninstalls Mu it should be safe to nuke the entire Mu installation folder.

**Comment by tmontes** [comment] 2021-08-23 17:11
Thanks for reporting @carlosperate. Will investigate, but the context is suspicious... 😉

**Comment by tmontes** [comment] 2021-08-28 22:32
RE-INVESTIGATION:

* Packaged Mu Editor with the bundled wheels by running `python -m mu.wheels` before `pup package`.
* Confirmed:
  * No Mu Editor installed / listed under *Programs and Features*.
  * No Mu Editor directory under ...`AppData\Local\Programs`.
* Installed MSI file.
* Lanched Mu -- took a while because I had cleaned the "local Mu things" directory, too.
* Ran minimal Python mode program with `turtle` + tried out the REPL.
* Quit Mu.
* Uninstalled Mu Editor from *Programs and Features*.
* No files left under ...`AppData\Local\Programs` -- the `Mu Editor` directory is gone.

SUMMARY:

The originally reported behaviour, much like my previous attempt, resulted from the fact that files not associated to  the version being uninstalled were found under the directory tree that should have been removed -- I take it that Windows installer is careful not to remove such "foreign" files, which feels reasonable.

CLOSING as "not a bug".

**Closed by tmontes** 2021-08-28 22:32 UTC
Labels: bug, @ plugin, : win
